// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimumSpanningTreeWithKruskal.Models;

#nullable disable

namespace MinimumSpanningTreeWithKruskal.Migrations
{
    [DbContext(typeof(GraphDbContext))]
    [Migration("20250623063155_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MinimumSpanningTreeWithKruskal.Models.Edge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<int>("TargetId")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("TargetId");

                    b.ToTable("Edges");
                });

            modelBuilder.Entity("MinimumSpanningTreeWithKruskal.Models.MSTEdge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EdgeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EdgeId");

                    b.ToTable("MSTEdges");
                });

            modelBuilder.Entity("MinimumSpanningTreeWithKruskal.Models.Node", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("MinimumSpanningTreeWithKruskal.Models.Edge", b =>
                {
                    b.HasOne("MinimumSpanningTreeWithKruskal.Models.Node", "Source")
                        .WithMany("OutgoingEdges")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinimumSpanningTreeWithKruskal.Models.Node", "Target")
                        .WithMany("IncomingEdges")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Source");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("MinimumSpanningTreeWithKruskal.Models.MSTEdge", b =>
                {
                    b.HasOne("MinimumSpanningTreeWithKruskal.Models.Edge", "Edge")
                        .WithMany()
                        .HasForeignKey("EdgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Edge");
                });

            modelBuilder.Entity("MinimumSpanningTreeWithKruskal.Models.Node", b =>
                {
                    b.Navigation("IncomingEdges");

                    b.Navigation("OutgoingEdges");
                });
#pragma warning restore 612, 618
        }
    }
}
